# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

   config.vm.define :controller do |controller|
    controller.vm.box = "ansible/tower"
    controller.vm.network :private_network, ip: "10.0.0.10"
    controller.vm.hostname = "controller"
  end

   config.vm.define :linux do |linux|
     linux.vm.box = "centos/7"
     linux.vm.network :private_network, ip: "10.0.0.11"
     linux.vm.hostname = "linux"
   end
   config.vm.define :linux2 do |linux2|
     linux2.vm.box = "centos/7"
     linux2.vm.network :private_network, ip: "10.0.0.12"
     linux2.vm.hostname = "linux2"
   end



end
